import { mkdirSync, writeFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import type { Project } from "@ai-wp/shared";
import { projectDir, composeCp } from "../docker/compose.js";
import { execWpCli } from "../docker/compose.js";

/**
 * GEN-06/GEN-07: child-theme generation & activation -- how the AI-derived
 * design system (color, font, mode from spec.design) actually reaches the
 * live site, instead of just being metadata the UI displays.
 *
 * A local staging copy is kept under
 * infrastructure/docker/projects/<id>/child-theme/ (not just inside the
 * container) so EXP-01's export tool can zip real files rather than having
 * to `docker compose cp` them back out at export time.
 */

export function childThemeSlug(parentSlug: string): string {
  return `${parentSlug}-ai-child`;
}

export function childThemeStagingDir(projectId: string, slug: string) {
  return join(projectDir(projectId), "child-theme", slug);
}
const stagingDir = childThemeStagingDir;

const GOOGLE_FONT_STACKS: Record<string, string> = {
  Inter: "'Inter', ui-sans-serif, system-ui, sans-serif",
  "IBM Plex Sans": "'IBM Plex Sans', ui-sans-serif, system-ui, sans-serif",
  Georgia: "Georgia, 'Times New Roman', serif",
};

function renderChildThemeCss(project: Project, parentSlug: string, parentName: string): string {
  const { primary_color, mode, font } = project.spec.design;
  const fontStack = GOOGLE_FONT_STACKS[font] ?? `'${font}', ui-sans-serif, system-ui, sans-serif`;
  const bg = mode === "dark" ? "#14151C" : "#FFFFFF";
  const text = mode === "dark" ? "#E7E8F0" : "#1B1D29";

  return `/*
Theme Name: ${project.spec.site.name} (AI Child)
Template: ${parentSlug}
Description: Generated child theme (of ${parentName}) applying the AI-derived design system (GEN-06) for "${project.spec.site.name}".
Version: 1.0.0
*/

:root {
  --ai-primary: ${primary_color};
  --ai-bg: ${bg};
  --ai-text: ${text};
  --ai-font: ${fontStack};
}

body {
  background-color: var(--ai-bg);
  color: var(--ai-text);
  font-family: var(--ai-font);
}

a, .wp-block-button__link, .wp-element-button {
  color: var(--ai-primary);
}

.wp-block-button__link, .wp-element-button {
  background-color: var(--ai-primary);
  color: #fff;
  border-radius: 6px;
}

.section-hero, .section-cta {
  padding: 3rem 1.5rem;
}

.section-features .wp-block-columns, .section-stats .wp-block-columns {
  gap: 2rem;
}

.feature-card, .pricing-tier, .team-member {
  border: 1px solid color-mix(in srgb, var(--ai-text) 12%, transparent);
  border-radius: 10px;
  padding: 1.25rem;
}

.stat-block h2 {
  color: var(--ai-primary);
}
`;
}

const CHILD_THEME_FUNCTIONS_PHP = `<?php
// Generated by the AI WordPress Builder (GEN-07). Enqueues the parent theme's
// stylesheet before this child theme's, per the standard WP child-theme
// pattern -- do not hand edit, regenerated on every design-system change.
add_action( 'wp_enqueue_scripts', function () {
    $parent = wp_get_theme()->parent();
    if ( $parent ) {
        wp_enqueue_style( 'ai-parent-style', get_template_directory_uri() . '/style.css' );
    }
    wp_enqueue_style(
        'ai-child-style',
        get_stylesheet_uri(),
        $parent ? array( 'ai-parent-style' ) : array(),
        wp_get_theme()->get( 'Version' )
    );
} );
`;

/** Writes the child theme locally, ships it into the wpcli container, and activates it. */
export async function generateAndActivateChildTheme(project: Project, parentSlug: string, parentName: string): Promise<string> {
  const slug = childThemeSlug(parentSlug);
  const dir = stagingDir(project.id, slug);
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });

  writeFileSync(join(dir, "style.css"), renderChildThemeCss(project, parentSlug, parentName));
  writeFileSync(join(dir, "functions.php"), CHILD_THEME_FUNCTIONS_PHP);

  // docker compose cp copies a whole directory when the source is a
  // directory -- lands at wp-content/themes/<slug>/{style.css,functions.php}.
  await composeCp(project.id, dir, `wpcli:/var/www/html/wp-content/themes/${slug}`);
  await execWpCli(project.id, ["theme", "activate", slug]);
  return slug;
}

/**
 * Re-renders just the CSS and re-ships it -- used by the incremental editor
 * (GEN-09) for design-only changes, without touching pages or plugins.
 * Also (re-)activates the child theme: a design edit is meaningless if the
 * child theme it's rewriting isn't actually the one currently serving the
 * site (e.g. a project whose child theme was generated but never
 * activated, or reactivated after a checkpoint restore). Activating an
 * already-active theme is a safe no-op.
 */
export async function regenerateChildThemeStyles(project: Project, parentSlug: string, parentName: string): Promise<void> {
  const slug = childThemeSlug(parentSlug);
  const dir = stagingDir(project.id, slug);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "style.css"), renderChildThemeCss(project, parentSlug, parentName));
  await composeCp(project.id, join(dir, "style.css"), `wpcli:/var/www/html/wp-content/themes/${slug}/style.css`);
  await execWpCli(project.id, ["theme", "activate", slug]);
}
