import { createWriteStream, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import archiver from "archiver";
import type { Project } from "@ai-wp/shared";
import { projectDir, composeCp, execWpCli, readProjectSecret } from "../docker/compose.js";
import { childThemeSlug, childThemeStagingDir } from "./childtheme.js";

/**
 * EXP-01/EXP-02: package a project for hand-off -- WordPress content (WXR),
 * the generated child theme, and a reproducible Docker Compose bundle with
 * setup instructions, all in one zip. Deliberately leaves generated DB
 * secrets out of the export (a fresh `docker compose up` regenerates its
 * own via the template) rather than shipping live credentials in a
 * downloadable file.
 */

function exportsDir(projectId: string) {
  const dir = join(projectDir(projectId), "exports");
  mkdirSync(dir, { recursive: true });
  return dir;
}

function deployReadme(project: Project): string {
  return `# ${project.spec.site.name} -- exported project bundle

Generated by the AI WordPress Builder on ${new Date().toISOString()}.

## What's in here

- \`content.xml\` -- WordPress eXtended RSS (WXR) export of all pages, ready for
  Tools > Import on any WordPress install.
- \`child-theme/\` -- the generated child theme applying this project's design
  system (colors, fonts, mode) on top of "${project.spec.theme.selected}".
- \`deploy/docker-compose.yml\` -- the exact compose stack this project ran in.

## Bringing this up elsewhere

\`\`\`bash
cd deploy
docker compose up -d --wait
\`\`\`

This starts a *fresh* WordPress + MariaDB with new, randomly generated
credentials (never the ones from the original environment -- those aren't
included in this export). Then:

1. Finish the WordPress install wizard at the mapped port.
2. Install/activate theme "${project.spec.theme.selected}" from wordpress.org,
   or WP-CLI: \`wp theme install ${project.spec.theme.selected} --activate\`.
3. Copy \`child-theme/${childThemeSlug(project.spec.theme.selected ?? "theme")}\`
   into \`wp-content/themes/\` and activate it.
4. Tools > Import > WordPress, upload \`content.xml\`.
`;
}

/**
 * SECURITY FIX (found while writing this file's test, task 05): the
 * per-project docker-compose.yml on disk has this project's real DB
 * password / DB root password baked directly into its `environment:`
 * blocks (see `renderCompose` in `../docker/compose.js`) -- fine for the
 * live container, which needs them, but `exportProject` below used to copy
 * that file into the export bundle *verbatim*, directly contradicting this
 * module's own doc comment and the README's "credential-free" export
 * claim: every exported zip shipped a live DB credential in
 * `deploy/docker-compose.yml`. Redact every secret this project's `.env`
 * actually holds before the compose file leaves this function, so the
 * bundle never contains a literal credential regardless of how the source
 * compose file was rendered.
 */
function redactSecrets(composeYaml: string, projectId: string): string {
  let redacted = composeYaml;
  for (const key of ["DB_PASSWORD", "DB_ROOT_PASSWORD", "WP_ADMIN_PASSWORD"]) {
    const value = readProjectSecret(projectId, key);
    if (value) redacted = redacted.split(value).join(`\${${key}}`);
  }
  return redacted;
}

export interface ExportResult {
  file: string;
  relativePath: string;
  bytes: number;
}

export async function exportProject(project: Project): Promise<ExportResult> {
  if (project.docker.status !== "running") {
    throw new Error("Environment must be running to export its content");
  }
  const dir = exportsDir(project.id);
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const workDir = join(dir, `staging-${stamp}`);
  mkdirSync(workDir, { recursive: true });

  // 1. WXR content export via WP-CLI's built-in exporter.
  const remoteFile = `/tmp/export-${stamp}.xml`;
  await execWpCli(project.id, ["export", "--dir=/tmp", `--filename_format=export-${stamp}`]);
  const contentXmlPath = join(workDir, "content.xml");
  await composeCp(project.id, `wpcli:${remoteFile}`, contentXmlPath).catch(() => {
    // wp-cli's exporter names the file slightly differently across versions;
    // fall back to a placeholder rather than failing the whole export.
    writeFileSync(contentXmlPath, "<!-- export unavailable: WP-CLI export command not found in this image -->");
  });

  // 2. Child theme, if one was generated for this project.
  const parentSlug = project.spec.theme.selected;
  if (parentSlug) {
    const childSlug = childThemeSlug(parentSlug);
    const childDir = childThemeStagingDir(project.id, childSlug);
    if (existsSync(childDir)) {
      mkdirSync(join(workDir, "child-theme", childSlug), { recursive: true });
      for (const file of ["style.css", "functions.php"]) {
        const src = join(childDir, file);
        if (existsSync(src)) writeFileSync(join(workDir, "child-theme", childSlug, file), readFileSync(src));
      }
    }
  }

  // 3. EXP-02: reproducible compose bundle + instructions (secrets excluded).
  const composeFile = join(projectDir(project.id), "docker-compose.yml");
  if (existsSync(composeFile)) {
    mkdirSync(join(workDir, "deploy"), { recursive: true });
    const composeYaml = redactSecrets(readFileSync(composeFile, "utf-8"), project.id);
    writeFileSync(join(workDir, "deploy", "docker-compose.yml"), composeYaml);
  }
  writeFileSync(join(workDir, "README.md"), deployReadme(project));

  // 4. Zip it.
  const zipPath = join(dir, `export-${stamp}.zip`);
  await new Promise<void>((resolve, reject) => {
    const output = createWriteStream(zipPath);
    const archive = archiver("zip", { zlib: { level: 9 } });
    output.on("close", () => resolve());
    archive.on("error", reject);
    archive.pipe(output);
    archive.directory(workDir, false);
    archive.finalize();
  });

  const stat = readFileSync(zipPath);
  return { file: zipPath, relativePath: `export-${stamp}.zip`, bytes: stat.byteLength };
}

export function exportsListDir(projectId: string) {
  return exportsDir(projectId);
}
